//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JAwelsAndDiamonds.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_JewelDetails
    {
        public int JewelId { get; set; }
        public string JewelName { get; set; }
        public decimal Price { get; set; }
        public int ReleaseYear { get; set; }
        public int CategoryId { get; set; }
        public string CategoryName { get; set; }
        public int BrandId { get; set; }
        public string BrandName { get; set; }
        public string CountryOfOrigin { get; set; }
        public string Class { get; set; }
    }
}
