//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JAwelsAndDiamonds.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class vw_TransactionDetails
    {
        public int TransactionId { get; set; }
        public int UserId { get; set; }
        public string Username { get; set; }
        public System.DateTime TransactionDate { get; set; }
        public string PaymentMethodName { get; set; }
        public string Status { get; set; }
        public int JewelId { get; set; }
        public string JewelName { get; set; }
        public decimal Price { get; set; }
        public int Quantity { get; set; }
        public Nullable<decimal> Subtotal { get; set; }
    }
}
